import { addDays, format, subDays } from "date-fns";

import type { LifeOSState } from "./types";

const d = (offset: number) => format(addDays(new Date(), offset), "yyyy-MM-dd");
const past = (offset: number) => format(subDays(new Date(), offset), "yyyy-MM-dd");

function streak(days: number, skip: number[] = []): string[] {
  const out: string[] = [];
  for (let i = 0; i < days; i++) {
    if (skip.includes(i)) continue;
    out.push(past(i));
  }
  return out;
}

export function createDemoState(): LifeOSState {
  return {
    user: { name: "Alex Morgan", initials: "AM", email: "alex@lifeos.app" },
    tasks: [
      {
        id: "t1",
        title: "Finish portfolio case study",
        notes: "Write the process section and export the final imagery.",
        completed: false,
        priority: "high",
        dueDate: d(0),
        dueTime: "10:30",
        category: "Design",
        tags: ["portfolio", "deep work"],
        estimate: 120,
        goalId: "g1",
        order: 0,
        createdAt: past(4),
      },
      {
        id: "t2",
        title: "Prepare tomorrow's presentation",
        completed: false,
        priority: "high",
        dueDate: d(1),
        dueTime: "09:00",
        category: "Work",
        tags: ["client"],
        estimate: 90,
        order: 1,
        createdAt: past(3),
      },
      {
        id: "t3",
        title: "Review project documentation",
        completed: false,
        priority: "medium",
        dueDate: d(0),
        dueTime: "13:00",
        category: "Work",
        tags: ["admin"],
        estimate: 45,
        order: 2,
        createdAt: past(2),
      },
      {
        id: "t4",
        title: "Read React documentation",
        completed: false,
        priority: "medium",
        dueDate: d(2),
        dueTime: "20:00",
        category: "Learning",
        tags: ["react"],
        estimate: 60,
        goalId: "g2",
        order: 3,
        createdAt: past(2),
      },
      {
        id: "t5",
        title: "Grocery shopping",
        completed: false,
        priority: "low",
        dueDate: d(0),
        dueTime: "18:30",
        category: "Personal",
        tags: ["errand"],
        estimate: 40,
        order: 4,
        createdAt: past(1),
      },
      {
        id: "t6",
        title: "Evening workout",
        completed: false,
        priority: "medium",
        dueDate: d(0),
        dueTime: "19:30",
        category: "Health",
        tags: ["routine"],
        estimate: 45,
        order: 5,
        createdAt: past(1),
      },
      {
        id: "t7",
        title: "Review project proposal",
        completed: false,
        priority: "high",
        dueDate: d(3),
        dueTime: "11:00",
        category: "Work",
        tags: ["client"],
        estimate: 50,
        order: 6,
        createdAt: past(1),
      },
      {
        id: "t8",
        title: "Add animations to portfolio",
        completed: false,
        priority: "low",
        dueDate: d(5),
        category: "Design",
        tags: ["portfolio"],
        estimate: 80,
        goalId: "g1",
        order: 7,
        createdAt: past(1),
      },
      {
        id: "t9",
        title: "Send invoice to client",
        completed: true,
        priority: "medium",
        dueDate: past(1),
        category: "Work",
        tags: ["finance"],
        estimate: 15,
        order: 8,
        createdAt: past(5),
      },
      {
        id: "t10",
        title: "Outline case study structure",
        completed: true,
        priority: "medium",
        dueDate: past(2),
        category: "Design",
        tags: ["portfolio"],
        estimate: 30,
        goalId: "g1",
        order: 9,
        createdAt: past(6),
      },
    ],
    habits: [
      {
        id: "h1",
        name: "Morning workout",
        icon: "Dumbbell",
        frequency: "daily",
        preferredTime: "Morning",
        goalPerWeek: 5,
        reminder: true,
        startDate: past(60),
        completions: streak(14, [12, 13]),
      },
      {
        id: "h2",
        name: "Read 20 minutes",
        icon: "BookOpen",
        frequency: "daily",
        preferredTime: "Evening",
        goalPerWeek: 7,
        reminder: true,
        startDate: past(90),
        completions: streak(21, [8, 14, 16]),
      },
      {
        id: "h3",
        name: "Drink water",
        icon: "Droplets",
        frequency: "daily",
        preferredTime: "Anytime",
        goalPerWeek: 7,
        reminder: false,
        startDate: past(45),
        completions: streak(10, [9]),
      },
      {
        id: "h4",
        name: "Journal",
        icon: "PenLine",
        frequency: "daily",
        preferredTime: "Evening",
        goalPerWeek: 5,
        reminder: true,
        startDate: past(30),
        completions: streak(12, [4, 8, 10]),
      },
      {
        id: "h5",
        name: "Meditate",
        icon: "Sparkle",
        frequency: "weekdays",
        preferredTime: "Morning",
        goalPerWeek: 5,
        reminder: false,
        startDate: past(25),
        completions: streak(9, [5, 7]),
      },
    ],
    goals: [
      {
        id: "g1",
        title: "Launch Portfolio Website",
        description: "Ship a personal site with three in-depth case studies and a writing section.",
        category: "Career",
        deadline: d(24),
        progress: 72,
        status: "on-track",
        importance: 5,
        milestones: [
          { id: "m1", title: "Design homepage", done: true },
          { id: "m2", title: "Build case study page", done: true },
          { id: "m3", title: "Add animations", done: false },
          { id: "m4", title: "Deploy website", done: false },
        ],
      },
      {
        id: "g2",
        title: "Learn React",
        description: "Work through the docs and build three practice apps.",
        category: "Learning",
        deadline: d(60),
        progress: 48,
        status: "on-track",
        importance: 4,
        milestones: [
          { id: "m5", title: "Finish core docs", done: true },
          { id: "m6", title: "Build a todo app", done: true },
          { id: "m7", title: "Learn data fetching patterns", done: false },
          { id: "m8", title: "Ship a side project", done: false },
        ],
      },
      {
        id: "g3",
        title: "Read 20 Books",
        description: "A steady reading habit — fiction and non-fiction alternating.",
        category: "Personal",
        deadline: d(120),
        progress: 65,
        status: "on-track",
        importance: 3,
        milestones: [
          { id: "m9", title: "Read 5 books", done: true },
          { id: "m10", title: "Read 10 books", done: true },
          { id: "m11", title: "Read 15 books", done: false },
          { id: "m12", title: "Read 20 books", done: false },
        ],
      },
      {
        id: "g4",
        title: "Run a half marathon",
        description: "Build up to 21km with a progressive training plan.",
        category: "Health",
        deadline: d(90),
        progress: 31,
        status: "at-risk",
        importance: 4,
        milestones: [
          { id: "m13", title: "Run 5km comfortably", done: true },
          { id: "m14", title: "Run 10km", done: false },
          { id: "m15", title: "Run 15km", done: false },
        ],
      },
    ],
    notes: [
      {
        id: "n1",
        title: "Portfolio Ideas",
        content:
          "Lead with the process, not the pixels.\n\n- Open each case study with the problem in one sentence\n- Show the messy middle: sketches, rejected directions\n- End with measurable outcome\n- Keep the writing voice warm and plain",
        tags: ["portfolio", "writing"],
        updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
      {
        id: "n2",
        title: "Books to Read",
        content:
          "1. The Creative Act — Rick Rubin\n2. Four Thousand Weeks\n3. Refactoring UI\n4. Deep Work\n5. The Pragmatic Programmer",
        tags: ["reading"],
        updatedAt: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
      },
      {
        id: "n3",
        title: "Project Brainstorm",
        content:
          "Small tools worth building:\n- A calm reading tracker\n- A weekly review generator\n- A habit heatmap widget\n\nPick one, ship it in a weekend.",
        tags: ["ideas", "side project"],
        updatedAt: new Date(Date.now() - 3 * 86400 * 1000).toISOString(),
      },
      {
        id: "n4",
        title: "Portfolio Inspiration",
        content:
          "References: editorial layouts, generous whitespace, muted natural palettes, serif accents used sparingly.",
        tags: ["portfolio", "design"],
        updatedAt: new Date(Date.now() - 4 * 86400 * 1000).toISOString(),
      },
    ],
    events: [
      {
        id: "e1",
        title: "Team Meeting",
        date: d(0),
        start: "10:00",
        end: "11:00",
        kind: "meeting",
        location: "Zoom",
      },
      { id: "e2", title: "Lunch", date: d(0), start: "13:30", end: "14:15", kind: "personal" },
      {
        id: "e3",
        title: "Design Review",
        date: d(0),
        start: "16:00",
        end: "17:00",
        kind: "meeting",
      },
      { id: "e4", title: "Gym", date: d(1), start: "09:00", end: "10:00", kind: "habit" },
      { id: "e5", title: "Client Call", date: d(1), start: "11:00", end: "11:45", kind: "meeting" },
      {
        id: "e6",
        title: "Deep work — case study",
        date: d(1),
        start: "14:00",
        end: "16:00",
        kind: "focus",
      },
      {
        id: "e7",
        title: "Dinner with Sam",
        date: d(2),
        start: "19:00",
        end: "21:00",
        kind: "personal",
      },
      {
        id: "e8",
        title: "Sprint planning",
        date: d(3),
        start: "09:30",
        end: "10:30",
        kind: "meeting",
      },
      { id: "e9", title: "Gym", date: d(3), start: "18:00", end: "19:00", kind: "habit" },
      {
        id: "e10",
        title: "Portfolio writing block",
        date: d(4),
        start: "09:00",
        end: "11:30",
        kind: "focus",
      },
    ],
    notifications: [
      {
        id: "no1",
        title: "Task due soon",
        body: "Finish portfolio case study is due in 2 hours.",
        time: "2h",
        read: false,
      },
      {
        id: "no2",
        title: "Habit streak",
        body: "You're on a 12-day Morning workout streak.",
        time: "5h",
        read: false,
      },
      {
        id: "no3",
        title: "AI plan updated",
        body: "Your focus plan was rebalanced for today.",
        time: "Today",
        read: false,
      },
      {
        id: "no4",
        title: "Goal deadline",
        body: "Launch Portfolio Website is due in 24 days.",
        time: "Yesterday",
        read: true,
      },
    ],
  };
}
