/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiPlannerRouteImport } from './routes/ai-planner'
import { Route as AiPrioritiesRouteImport } from './routes/ai-priorities'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WeeklyPlanRouteImport } from './routes/weekly-plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlannerRoute = AiPlannerRouteImport.update({
  id: '/ai-planner',
  path: '/ai-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPrioritiesRoute = AiPrioritiesRouteImport.update({
  id: '/ai-priorities',
  path: '/ai-priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyPlanRoute = WeeklyPlanRouteImport.update({
  id: '/weekly-plan',
  path: '/weekly-plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-planner': typeof AiPlannerRoute
  '/ai-priorities': typeof AiPrioritiesRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/weekly-plan': typeof WeeklyPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-planner': typeof AiPlannerRoute
  '/ai-priorities': typeof AiPrioritiesRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/weekly-plan': typeof WeeklyPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-planner': typeof AiPlannerRoute
  '/ai-priorities': typeof AiPrioritiesRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/weekly-plan': typeof WeeklyPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-planner'
    | '/ai-priorities'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/goals'
    | '/habits'
    | '/notes'
    | '/settings'
    | '/tasks'
    | '/weekly-plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-planner'
    | '/ai-priorities'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/goals'
    | '/habits'
    | '/notes'
    | '/settings'
    | '/tasks'
    | '/weekly-plan'
  id:
    | '__root__'
    | '/'
    | '/ai-planner'
    | '/ai-priorities'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/goals'
    | '/habits'
    | '/notes'
    | '/settings'
    | '/tasks'
    | '/weekly-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPlannerRoute: typeof AiPlannerRoute
  AiPrioritiesRoute: typeof AiPrioritiesRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  GoalsRoute: typeof GoalsRoute
  HabitsRoute: typeof HabitsRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  WeeklyPlanRoute: typeof WeeklyPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-planner': {
      id: '/ai-planner'
      path: '/ai-planner'
      fullPath: '/ai-planner'
      preLoaderRoute: typeof AiPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-priorities': {
      id: '/ai-priorities'
      path: '/ai-priorities'
      fullPath: '/ai-priorities'
      preLoaderRoute: typeof AiPrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly-plan': {
      id: '/weekly-plan'
      path: '/weekly-plan'
      fullPath: '/weekly-plan'
      preLoaderRoute: typeof WeeklyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPlannerRoute: AiPlannerRoute,
  AiPrioritiesRoute: AiPrioritiesRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  GoalsRoute: GoalsRoute,
  HabitsRoute: HabitsRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  WeeklyPlanRoute: WeeklyPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
